### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by seasonedfish** [iamnyasha/minimma#1]
I found this repo from the Astro themes website, so I assume it was made to be used by others, but without a license file, it's unclear.

> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

https://choosealicense.com/

**Comment by fool-stack-dev** [comment]
Under which license is https://github.com/iamnyasha/minimma licensed?

**Comment by seasonedfish** [comment]
Thanks 😄
